version: '2'
services:
  ocsg6:
    image: netapps/ocsg:6.0
    ports:
      - "7001:7001"
    depends_on:
      - mysqldb
    links:
      - mysqldb
  mysqldb:
    image: mysql:5.6
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=welcome1
      - MYSQL_DATABASE=ocsg
      - MYSQL_USER=ocsg
      - MYSQL_PASSWORD=ocsg
  ocsg6pte:
    image: netapps/ocsgpte:6.0
    ports:
      - "5900:5900"
    depends_on:
      - ocsg6
    links:
      - ocsg6
      - mysqldb
